Fixing detach that is called multiple times
robotology/cer pull request #125
Opened 2021-12-16 09:14 UTC by ste93

2021-12-16 09:16 UTC, ste93 commented
@elandini84

2022-05-19 13:04 UTC, randaz81 requested changes

2022-05-19 13:04 UTC, randaz81 commented on cermod/cerOdometry/CerOdometry.cpp
> -    detach();
Not sure about this, to be verified.

2022-05-19 13:04 UTC, randaz81 commented on cermod/cerOdometry/CerOdometry.cpp
> -    detach();
ok!

2022-05-19 16:01 UTC, randaz81 approved these changes

2022-05-19 16:01 UTC, merged